POSITIONS=$1
INPUT_BAM_FP=$2
SAMPLE_NAME=$3

FILTERED_BAM_DIR=$4
READCOUNTS_DIR=$5

FASTA=$6

FILTERED_FP="$FILTERED_BAM_DIR$SAMPLE_NAME"
FILTERED_FP+=".bam"
READCOUNT_FP="$READCOUNTS_DIR$SAMPLE_NAME"
READCOUNT_FP+=".readcount"

samtools index $INPUT_BAM_FP
samtools view -h -L $POSITIONS -o $FILTERED_FP $INPUT_BAM_FP
samtools index $FILTERED_FP
bam-readcount -w 1 -f $FASTA -l $POSITIONS $FILTERED_FP > $READCOUNT_FP
